### ISSUE TITLE
Matching TFT Firmware

### ISSUE THREAD

**Issue by maverick1872** [digant73/Artillery-Sidewinder-X1_releases_main_board#1]
Hey Digant! I am getting ready to flash your [latest mainboard firmware](https://github.com/digant73/Artillery-Sidewinder-X1_releases_main_board/tree/master/artillery_swx1_marlin_fw_2.0.9.1/bltouch_waggster_mod_(z_max_used)) for my sidewinder x1 as I just installed a BLTouch. Curious what TFT firmware I should be flashing to match. As far as I could tell all of [these that you also host](https://github.com/digant73/Artillery-Sidewinder-X1_releases_tft) are only for the BTT TFT w/ the rotary dial which I don't have (rocking stock TFT).

**Comment by digant73** [comment]
hi


You should consider only this four fw 
https://github.com/digant73/Marlin/tags

Those are the source code for the binary I provided in the Thingiverse's 
download page.

Both four versions are configured to support rotary encoder but it is 
not enabled.

Read the M600 doc (in the download page) if you want to enable Marlin 
Mode (and rotary encoder).


Antonio



Il 4/3/2022 9:46 PM, Jonathon Terry ha scritto:

**Comment by maverick1872** [comment]
Referencing a tag is most appropriate, I agree. I ended up flashing the Artillery Sidewinder TFT Firmware found here: https://www.thingiverse.com/thing:5317601/files

In the future though it would likely be easier to tag TFT releases as well. Maybe even use thingiverse to direct people to the Github tags for both the mainboard firmware or the TFT firmware as it's much better suited for "releasing" than thingiverse.
